spring:
  datasource:
    url: jdbc:mysql://192.168.1.131:3306/sfg_prod
    username: sfg_prod_user
    password: prod_pass
    platform: mysql    
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false