insert into UNIT_OF_MEASURE (description) values ('Tablespoon');
insert into UNIT_OF_MEASURE (description) values ('Teaspoon');
insert into UNIT_OF_MEASURE (description) values ('Cup');
insert into UNIT_OF_MEASURE (description) values ('Pint');
insert into UNIT_OF_MEASURE (description) values ('Pinch');
insert into UNIT_OF_MEASURE (description) values ('Dash');
insert into UNIT_OF_MEASURE (description) values ('Ounce');
insert into UNIT_OF_MEASURE (description) values ('Each');
insert into CATEGORY (description) values ('American');
insert into CATEGORY (description) values ('French');
insert into CATEGORY (description) values ('Italian');
insert into CATEGORY (description) values ('Mexican');
insert into CATEGORY (description) values ('Snacks');
insert into CATEGORY (description) values ('Fast Food');
insert into CATEGORY (description) values ('Side Dishes');
